// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD63jDs8zx_kV-bfwddX6th3bH1CMj-gEk',
    appId: '1:12372904825:android:9d90024a15b8da0922fda8',
    messagingSenderId: '12372904825',
    projectId: 'mightydelivery-10da9',
    storageBucket: 'mightydelivery-10da9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBAenKVvWlnQe7EIOD0s-GpZbnZSq-Zk',
    appId: '1:12372904825:ios:64a6327db511ecf822fda8',
    messagingSenderId: '12372904825',
    projectId: 'mightydelivery-10da9',
    storageBucket: 'mightydelivery-10da9.appspot.com',
    androidClientId: '12372904825-41ti53tdtmva3p3hjf5vs58r4os7ss5o.apps.googleusercontent.com',
    iosClientId: '12372904825-56ffelkeqmcgjsd5c441vto76hduigc0.apps.googleusercontent.com',
    iosBundleId: 'com.mighty.delivery1',
  );

}